C     * general variables *
      integer     maxrange, PPMAX
      parameter   (maxrange = 2000)
      parameter   (PPMAX = 100)
      integer     maxframe
      Common /GEN/ maxframe

C     * PARAMETERS
      INTEGER    NPMAX, NLMAX, NMMAX, NMAX
C      PARAMETER (NPMAX   = 300000)
      PARAMETER (NPMAX   = 10054)
      PARAMETER (NLMAX   = 16)
      PARAMETER (NMMAX   = 40)
      PARAMETER (NMAX    = NPMAX*NLMAX*NMMAX)

C     * INTEGER VARIABLES AND PROGRAM CONTROL
      INTEGER           NP,NL,NM
      INTEGER           ISTEP,NSTEP,NEQSTEP,NPRINT,NCALC, NCOM,NEQCOM,
     :                  nsurf
      COMMON /INTVAR/   NL,NM,ISTEP,NSTEP,NEQSTEP,NPRINT,NCALC,
     :     NCOM,NEQCOM, nsurf
      REAL               DT
      common /REALVAR/   DT

C     * MATH PARAMETERS
      REAL         PI, TWOPI, TWOPIO3, TWOO15
      PARAMETER    (PI    = 3.141592654)
      PARAMETER    (TWOPI = 2.0*PI)
      PARAMETER    (TWOPIO3 = TWOPI/3.)
      PARAMETER    (TWOO15  = 2. / 15.)

C     * LJ POTENTIAL
      REAL       RMIN, RMINSQ, ALPHA, BETA, S_A, S_C, M_A, M_C
      PARAMETER (RMIN    = 1.122462)
      PARAMETER (RMINSQ  = 1.259921)
      REAL       EBB
      PARAMETER (ALPHA    = 3.1730728678)
      PARAMETER (BETA     = -0.856228645)
      COMMON /PREAL/ EBB, S_A, S_C, M_A, M_C

C     * CELL LISTS PARAMETERS AND VARIABLES
      INTEGER TOTMAX
      PARAMETER (TOTMAX  = 2000000)
      REAL RC, RCSQ
      INTEGER MX,MY,MZ, NCELL,LIST(TOTMAX),HEAD(TOTMAX),MAP(13*TOTMAX)
      COMMON /CELLINT/ MX,MY,MZ, NCELL, LIST, HEAD, MAP, RC,RCSQ

C     * ENERGIES
      DOUBLE PRECISION    KE, PELJ, PELJSQ, PEBOND, PECORE
      COMMON /ENERG/      KE, PELJ, PELJSQ, PEBOND, PECORE

C     * SIMULATION BOX VARIABLES
      DOUBLE PRECISION LX,LY,LZ,LXO2,LYO2,LZO2,AREAXY,VOLUMEG,GAP,
     :     VOLUME,RCSUR, RHO, RHO_AV, L_AV
      COMMON /BOXVAR/ LX,LY,LZ,LXO2,LYO2,LZO2,AREAXY,VOLUMEG,GAP,
     :     VOLUME,RCSUR, RHO, RHO_AV, L_AV

C	* HISTOGRAM-RELATED
      INTEGER      NBINMAX
      PARAMETER  ( NBINMAX = 20000 )

C     * other
      INTEGER QDES
      REAL    HEIGHT
      COMMON /OTHER/ QDES, HEIGHT
